name: Pull Request

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches: main

jobs:
  pr:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the package
        run: swift build
